permissions:
  contents: read
name: run-ci-tests
on: [push, pull_request, workflow_dispatch]
jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v5.0.0
        with:
          python-version: ^3.8
      - uses: pre-commit/action@v3.0.0
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ^3.8
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt .
      - name: Run unit tests
        run: cd tests/ && /bin/bash run_all_tests.sh
